# -*- coding: utf-8 -*-
"""1431. Kids With the Greatest Number of Candies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TOT1Kr2zpsZTBmpJxU5kTHlvPF83iTk
"""

from typing import List

class Solution:
    def kidsWithCandies(self, candies: List[int], extraCandies: int) -> List[bool]:
        max_candies = max(candies)  # Find the maximum candies any kid has
        result = []

        for candy in candies:
            # Check if the current kid's candies plus extraCandies is at least max_candies
            result.append(candy + extraCandies >= max_candies)

        return result