# -*- coding: utf-8 -*-
"""238. Product of Array Except Self.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G53d8ldaKirzFE2yKgVxPTKog5sltaZ0
"""

from typing import List

class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        length = len(nums)

        # Initialize the answer array where each value is initially 1
        answer = [1] * length

        # Calculate the prefix product for each element and store it in answer array
        prefix = 1
        for i in range(length):
            answer[i] = prefix
            prefix *= nums[i]

        # Calculate the suffix product for each element and multiply it with the existing value in answer array
        suffix = 1
        for i in range(length - 1, -1, -1):
            answer[i] *= suffix
            suffix *= nums[i]

        return answer