# -*- coding: utf-8 -*-
"""334. Increasing Triplet Subsequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G53d8ldaKirzFE2yKgVxPTKog5sltaZ0
"""

from typing import List

class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        # Initialize two variables to keep track of the smallest and second smallest elements
        first = float('inf')
        second = float('inf')

        # Traverse the array
        for num in nums:
            if num <= first:
                # Update 'first' if the current number is smaller
                first = num
            elif num <= second:
                # Update 'second' if current number is greater than 'first' but smaller than 'second'
                second = num
            else:
                # If we find a number greater than both 'first' and 'second', return True
                return True

        # If no such triplet is found, return False
        return False