# -*- coding: utf-8 -*-
"""605. Can Place Flowers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2N2CM4hIeuBGwMDr5dQhTm-71k4KwNK
"""

from typing import List

class Solution:
    def canPlaceFlowers(self, flowerbed: List[int], n: int) -> bool:
        count = 0  # Count of flowers we can plant
        length = len(flowerbed)

        for i in range(length):
            # Check if the current plot is empty and has empty neighbors (or is at the boundary)
            if flowerbed[i] == 0:
                # Check the left neighbor (or if it's the first plot)
                empty_left = (i == 0) or (flowerbed[i - 1] == 0)
                # Check the right neighbor (or if it's the last plot)
                empty_right = (i == length - 1) or (flowerbed[i + 1] == 0)

                if empty_left and empty_right:
                    # Plant a flower here
                    flowerbed[i] = 1
                    count += 1

                    # If we have planted enough flowers, return True
                    if count >= n:
                        return True

        # If we exit the loop, check if we planted enough flowers
        return count >= n