# -*- coding: utf-8 -*-
"""1072. Flip Columns For Maximum Number of Equal Rows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_NyjNabR4t8oTzmBr9aE4hpQ1t6T057
"""

class Solution:
    def maxEqualRowsAfterFlips(self, matrix: List[List[int]]) -> int:
        count = defaultdict(int)
        for row in matrix:
            row_key = tuple(row)
            if row[0]:
                row_key = tuple([0 if n else 1 for n in row])
            count[row_key] += 1
        return max(count.values())