# -*- coding: utf-8 -*-
"""118. Pascal's Triangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kj-xnsM8kbFVwHhwI85YYmaEBCWtCZg0
"""

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        res = [[1]]

        for i in range(numRows - 1):
            temp = [0] + res[-1] + [0]
            row = []
            for j in range(len(res[-1]) + 1):
                row.append(temp[j] + temp[j + 1])
            res.append(row)
        return res