# -*- coding: utf-8 -*-
"""11. Container With Most Water.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr7W4kpBRfyE7AQYY_7Low_8ypzz8HOs
"""

from typing import List

class Solution:
    def maxArea(self, height: List[int]) -> int:
        left, right = 0, len(height) - 1
        max_area = 0

        while left < right:
            # Calculate the current area
            width = right - left
            area = width * min(height[left], height[right])
            # Update max_area if the current area is larger
            max_area = max(max_area, area)

            # Move the pointer pointing to the shorter line
            if height[left] < height[right]:
                left += 1
            else:
                right -= 1

        return max_area