# -*- coding: utf-8 -*-
"""1207. Unique Number of Occurrences.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxAC4yR_-Z5dojt-oQDzgT-fr_IO9qCC
"""

class Solution:
    def uniqueOccurrences(self, arr: List[int]) -> bool:
        # Count occurrences of each element in arr
        count = Counter(arr)

        # Get the frequencies of occurrences
        occurrences = list(count.values())

        # Check if all occurrences are unique by comparing the length of occurrences list with the length of the set of occurrences
        return len(occurrences) == len(set(occurrences))