# -*- coding: utf-8 -*-
"""1346. Check If N and Its Double Exist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCO466HUMIjHuuvqo8enqaqT7Ifz9mBo
"""

class Solution:
    def checkIfExist(self, arr: List[int]) -> bool:
        seen = set()

        for num in arr:
            if 2 * num in seen or (num % 2 == 0 and num // 2 in seen):
                return True
            seen.add(num)

        return False