# -*- coding: utf-8 -*-
"""1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y1acoNbC4JH3Ab2S2p6Bywr5TneraeJ
"""

class Solution:
    def isPrefixOfWord(self, sentence: str, searchWord: str) -> int:
        words = sentence.split()

        for index, word in enumerate(words):
            if word.startswith(searchWord):
                return index + 1

        return -1