# -*- coding: utf-8 -*-
"""1456. Maximum Number of Vowels in a Substring of Given Length.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pDPqcnacs5XN5LXupPLvzHS1YBX5iJd
"""

class Solution:
    def maxVowels(self, s: str, k: int) -> int:
        vowels = {'a', 'e', 'i', 'o', 'u'}
        # Count vowels in the first window of size k
        current_vowel_count = sum(1 for i in range(k) if s[i] in vowels)
        max_vowel_count = current_vowel_count

        # Slide the window across the string
        for i in range(k, len(s)):
            # Remove the effect of the character that's sliding out of the window
            if s[i - k] in vowels:
                current_vowel_count -= 1
            # Add the effect of the character that's sliding into the window
            if s[i] in vowels:
                current_vowel_count += 1
            # Update the maximum vowel count
            max_vowel_count = max(max_vowel_count, current_vowel_count)

        return max_vowel_count