# -*- coding: utf-8 -*-
"""1462. Course Schedule IV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpVFyNM24h-nF9dKZx0842SxfCalg1_e
"""

class Solution:
    def checkIfPrerequisite(
        self, n: int, prerequisites: List[List[int]], queries: List[List[int]]
    ) -> List[bool]:
        f = [[False] * n for _ in range(n)]
        for a, b in prerequisites:
            f[a][b] = True
        for k in range(n):
            for i in range(n):
                for j in range(n):
                    if f[i][k] and f[k][j]:
                        f[i][j] = True
        return [f[a][b] for a, b in queries]