# -*- coding: utf-8 -*-
"""1493. Longest Subarray of 1's After Deleting One Element.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pDPqcnacs5XN5LXupPLvzHS1YBX5iJd
"""

class Solution:
    def longestSubarray(self, nums: List[int]) -> int:
        left = 0
        max_length = 0
        zero_count = 0

        # Expand the window with the right pointer
        for right in range(len(nums)):
            # If we encounter a zero, increase the zero count
            if nums[right] == 0:
                zero_count += 1

            # If zero count exceeds 1, shrink the window from the left
            while zero_count > 1:
                if nums[left] == 0:
                    zero_count -= 1
                left += 1

            # Update the maximum length, subtracting 1 to account for the required deletion
            max_length = max(max_length, right - left)

        return max_length