# -*- coding: utf-8 -*-
"""1539. Kth Missing Positive Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

class Solution:
    def findKthPositive(self, arr: List[int], k: int) -> int:
        l, r = 0, len(arr) - 1
        while l <= r:
            m = (l + r) // 2
            missing = arr[m] - m - 1

            if missing < k:
                l = m + 1
            else:
                r = m - 1
        return r + k + 1