# -*- coding: utf-8 -*-
"""1574. Shortest Subarray to be Removed to Make Array Sorted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpH9KtTECNWqMNTcCbzZlsDimFqCZ9io
"""

class Solution:
    def findLengthOfShortestSubarray(self, arr):
        N = len(arr)

        r = N - 1
        while r > 0 and arr[r - 1] <= arr[r]:
            r -= 1

        if r == 0:
            return 0

        res = r

        l = 0
        while l < N and (l == 0 or arr[l - 1] <= arr[l]):
            while r < N and arr[l] > arr[r]:
                r += 1

            res = min(res, r - l - 1)
            l += 1

        return res