# -*- coding: utf-8 -*-
"""162. Find Peak Element.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faCIIy4DcvKIPFhe-6fKEts_pPyqy_PZ
"""

class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
      l, r = 0, len(nums) - 1
      while l <= r:
        m = l + (r - l) // 2
        # left neighbour greater
        if m > 0 and nums[m] < nums[m - 1]:
            r = m - 1
        # right neighbour greater
        elif m < len(nums) - 1 and nums[m] < nums[m + 1]:
            l = m + 1
        else:
            return m