# -*- coding: utf-8 -*-
"""1652. Defuse the Bomb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URvySlkRixdVynBRUFyD-G3T-HN_h2g3
"""

class Solution:
    def decrypt(self, code: list[int], k: int) -> list[int]:
        n = len(code)

        if k == 0:
            return [0] * n

        result = [0] * n

        if k > 0:
            for i in range(n):
                result[i] = sum(code[(i + j) % n] for j in range(1, k + 1))

        else:
            for i in range(n):
                result[i] = sum(code[(i + j) % n] for j in range(k, 0))

        return result