# -*- coding: utf-8 -*-
"""1679. Max Number of K-Sum Pairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr7W4kpBRfyE7AQYY_7Low_8ypzz8HOs
"""

from typing import List
from collections import defaultdict

class Solution:
    def maxOperations(self, nums: List[int], k: int) -> int:
        count = defaultdict(int)
        operations = 0

        for num in nums:
            complement = k - num
            # Check if the complement is available in the dictionary
            if count[complement] > 0:
                operations += 1
                count[complement] -= 1
            else:
                count[num] += 1

        return operations