# -*- coding: utf-8 -*-
"""1752. Check if Array Is Sorted and Rotated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHooiJVSGNXBCJeoSWF9eIncC0IoVGRw
"""

class Solution:
    def check(self, nums: List[int]) -> bool:
        return sum(nums[i - 1] > v for i, v in enumerate(nums)) <= 1