# -*- coding: utf-8 -*-
"""1760. Minimum Limit of Balls in a Bag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpVFyNM24h-nF9dKZx0842SxfCalg1_e
"""

class Solution:
    def minimumSize(self, nums: List[int], maxOperations: int) -> int:
        def can_divide_with_penalty(penalty):
            operations = 0
            for balls in nums:
                if balls > penalty:
                    operations += (balls - 1) // penalty
            return operations <= maxOperations

        left, right = 1, max(nums)
        result = right

        while left <= right:
            mid = (left + right) // 2
            if can_divide_with_penalty(mid):
                result = mid
                right = mid - 1
            else:
                left = mid + 1

        return result