# -*- coding: utf-8 -*-
"""1792. Maximum Average Pass Ratio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def maxAverageRatio(self, classes: List[List[int]], extraStudents: int) -> float:
        heap = []
        for passes, total in classes:
            gain = (passes + 1) / (total + 1) - passes / total
            heapq.heappush(heap, (-gain, passes, total))
        for _ in range(extraStudents):
            _, passes, total = heapq.heappop(heap)
            passes += 1
            total += 1
            new_gain = (passes + 1) / (total + 1) - passes / total
            heapq.heappush(heap, (-new_gain, passes, total))
        return sum(passes / total for _, passes, total in heap) / len(classes)