# -*- coding: utf-8 -*-
"""1829. Maximum XOR for Each Query.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5nVL5TV2RZD-Riu88wRfKSOiIe0Oc77
"""

class Solution:
    def getMaximumXor(self, nums: List[int], maximumBit: int) -> List[int]:
        xor = 0
        for n in nums:
            xor ^= n

        mask = (1 << maximumBit) - 1
        answer = []
        for n in reversed(nums):
            answer.append(xor ^ mask)
            xor ^= n

        return answer