# -*- coding: utf-8 -*-
"""1975. Maximum Matrix Sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iP24vtSYrykI5jEonykUHLSfRx77J41m
"""

class Solution:
    def maxMatrixSum(self, matrix: List[List[int]]) -> int:
        res = 0
        neg_cnt = 0
        mat_min = float("inf")
        for row in matrix:
            for n in row:
                res += abs(n)
                mat_min = min(mat_min, abs(n))
                if n < 0:
                    neg_cnt += 1

        if neg_cnt & 1:
            res -= 2 * mat_min

        return res