# -*- coding: utf-8 -*-
"""200. Number of Islands.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb1VF4vV9uTMPh4NhbL5sV074kBqKVRM
"""

class Solution:
    def numIslands(self, grid: list[list[str]]) -> int:
        def dfs(r, c):
            if r < 0 or r >= m or c < 0 or c >= n or grid[r][c] == '0':
                return

            grid[r][c] = '0'

            for dr, dc in directions:
                dfs(r + dr, c + dc)

        m, n = len(grid), len(grid[0])
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        island_count = 0

        for i in range(m):
            for j in range(n):
                if grid[i][j] == '1':
                    island_count += 1
                    dfs(i, j)

        return island_count