# -*- coding: utf-8 -*-
"""2064. Minimized Maximum of Products Distributed to Any Store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpH9KtTECNWqMNTcCbzZlsDimFqCZ9io
"""

class Solution:
    def minimizedMaximum(self, n: int, quantities: List[int]) -> int:
        def can_distribute(x):
            stores = 0
            for q in quantities:
                stores += math.ceil(q / x)
            return stores <= n

        l, r = 1, max(quantities)
        res = 0
        while l <= r:
            x = (l + r) // 2
            if can_distribute(x):
                res = x
                r = x - 1
            else:
                l = x + 1

        return res