# -*- coding: utf-8 -*-
"""2109. Adding Spaces to a String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y1acoNbC4JH3Ab2S2p6Bywr5TneraeJ
"""

class Solution:
    def addSpaces(self, s: str, spaces: List[int]) -> str:
        result = []
        space_idx = 0
        n = len(spaces)

        for i, char in enumerate(s):
            if space_idx < n and i == spaces[space_idx]:
                result.append(' ')
                space_idx += 1
            result.append(char)

        return ''.join(result)