# -*- coding: utf-8 -*-
"""2182. Construct String With Repeat Limit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def repeatLimitedString(self, s: str, repeatLimit: int) -> str:
        freq = Counter(s)
        max_heap = [(-ord(char), char, count) for char, count in freq.items()]
        heapq.heapify(max_heap)
        result = []
        while max_heap:
            _, char, count = heapq.heappop(max_heap)
            times = min(count, repeatLimit)
            result.append(char * times)
            count -= times
            if count > 0:
                if max_heap:
                    _, next_char, next_count = heapq.heappop(max_heap)
                    result.append(next_char)
                    next_count -= 1
                    if next_count > 0:
                        heapq.heappush(max_heap, (-ord(next_char), next_char, next_count))
                else:
                    break
                heapq.heappush(max_heap, (-ord(char), char, count))

        return ''.join(result)