# -*- coding: utf-8 -*-
"""2215. Find the Difference of Two Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxAC4yR_-Z5dojt-oQDzgT-fr_IO9qCC
"""

class Solution:
    def findDifference(self, nums1: List[int], nums2: List[int]) -> List[List[int]]:
        # Convert both lists to sets to remove duplicates and allow set operations
        set1, set2 = set(nums1), set(nums2)

        # Find elements in set1 that are not in set2 and vice versa
        result1 = list(set1 - set2)
        result2 = list(set2 - set1)

        return [result1, result2]