# -*- coding: utf-8 -*-
"""2342. Max Sum of a Pair With Equal Sum of Digits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b2CB46rUfLyBasmK7CplQX16e9EVyjI
"""

class Solution:
    def maximumSum(self, nums: List[int]) -> int:
        d = defaultdict(int)
        ans = -1
        for v in nums:
            x, y = 0, v
            while y:
                x += y % 10
                y //= 10
            if x in d:
                ans = max(ans, d[x] + v)
            d[x] = max(d[x], v)
        return ans