# -*- coding: utf-8 -*-
"""2352. Equal Row and Column Pairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCO466HUMIjHuuvqo8enqaqT7Ifz9mBo
"""

class Solution:
    def equalPairs(self, grid: List[List[int]]) -> int:
        row_count = Counter(tuple(row) for row in grid)

        count = 0
        for col in zip(*grid):
            count += row_count[tuple(col)]

        return count