# -*- coding: utf-8 -*-
"""2364. Count Number of Bad Pairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b2CB46rUfLyBasmK7CplQX16e9EVyjI
"""

class Solution:
    def countBadPairs(self, nums: List[int]) -> int:
        cnt = Counter()
        ans = 0
        for i, x in enumerate(nums):
            ans += i - cnt[i - x]
            cnt[i - x] += 1
        return ans