# -*- coding: utf-8 -*-
"""2415. Reverse Odd Levels of Binary Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

class Solution:
    def reverseOddLevels(self, root: Optional[TreeNode]) -> Optional[TreeNode]:
        def dfs(left, right, level):
            if not left or not right:
                return

            if level % 2 == 1:
                left.val, right.val = right.val, left.val

            dfs(left.left, right.right, level + 1)
            dfs(left.right, right.left, level + 1)

        if root:
            dfs(root.left, root.right, 1)
        return root