# -*- coding: utf-8 -*-
"""2516. Take K of Each Character From Left and Right.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URvySlkRixdVynBRUFyD-G3T-HN_h2g3
"""

class Solution:
    def takeCharacters(self, s: str, k: int) -> int:
        cnt = Counter(s)
        if any(cnt[c] < k for c in "abc"):
            return -1
        mx = j = 0
        for i, c in enumerate(s):
            cnt[c] -= 1
            while cnt[c] < k:
                cnt[s[j]] += 1
                j += 1
            mx = max(mx, i - j + 1)
        return len(s) - mx