# -*- coding: utf-8 -*-
"""2554. Maximum Number of Integers to Choose From a Range I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpVFyNM24h-nF9dKZx0842SxfCalg1_e
"""

class Solution:
    def maxCount(self, banned: List[int], n: int, maxSum: int) -> int:
        banned_set = set(banned)
        count = 0
        total_sum = 0

        for num in range(1, n + 1):
            if num not in banned_set:
                if total_sum + num > maxSum:
                    break
                total_sum += num
                count += 1

        return count