# -*- coding: utf-8 -*-
"""2558. Take Gifts From the Richest Pile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def pickGifts(self, gifts: List[int], k: int) -> int:
        max_heap = [-gift for gift in gifts]
        heapq.heapify(max_heap)

        for _ in range(k):
            max_gifts = -heapq.heappop(max_heap)
            remaining_gifts = math.floor(math.sqrt(max_gifts))
            heapq.heappush(max_heap, -remaining_gifts)
        return -sum(max_heap)