# -*- coding: utf-8 -*-
"""2593. Find Score of an Array After Marking All Elements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def findScore(self, nums):
        n = len(nums)
        marked = [False] * n
        heap = []

        for i, num in enumerate(nums):
            heappush(heap, (num, i))

        score = 0

        while heap:
            value, index = heappop(heap)

            if marked[index]:
                continue

            score += value

            marked[index] = True
            if index > 0:
                marked[index - 1] = True
            if index < n - 1:
                marked[index + 1] = True

        return score