# -*- coding: utf-8 -*-
"""275. H-Index II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

class Solution:
    def hIndex(self, citations: List[int]) -> int:
        n = len(citations)
        l, r = 0, n - 1

        while l <= r:
            mid = l + (r - l) // 2
            if citations[mid] < n - mid:
                l = mid + 1
            else:
                r = mid - 1

        return n - l