# -*- coding: utf-8 -*-
"""2779. Maximum Beauty of an Array After Applying Operation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpVFyNM24h-nF9dKZx0842SxfCalg1_e
"""

class Solution:
    def maximumBeauty(self, nums: List[int], k: int) -> int:
        ranges = []
        for num in nums:
            ranges.append((num - k, num + k))

        ranges.sort()

        events = []
        for start, end in ranges:
            events.append((start, 1))
            events.append((end + 1, -1))

        events.sort()

        max_beauty = 0
        current_overlap = 0
        for point, event_type in events:
            current_overlap += event_type
            max_beauty = max(max_beauty, current_overlap)

        return max_beauty