# -*- coding: utf-8 -*-
"""2825. Make String a Subsequence Using Cyclic Increments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y1acoNbC4JH3Ab2S2p6Bywr5TneraeJ
"""

class Solution:
    def canMakeSubsequence(self, str1: str, str2: str) -> bool:
        i, j = 0, 0
        n, m = len(str1), len(str2)

        while i < n and j < m:
            if str1[i] == str2[j] or chr((ord(str1[i]) - ord('a') + 1) % 26 + ord('a')) == str2[j]:
                j += 1
            i += 1

        return j == m