# -*- coding: utf-8 -*-
"""283. Move Zeroes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ffn_EBAB8mNUW_ygH9Pz9TsDfArwL6w
"""

from typing import List

class Solution:
    def moveZeroes(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        # Pointer for the position of the next non-zero element
        non_zero_index = 0

        # First pass: Move all non-zero elements to the front
        for i in range(len(nums)):
            if nums[i] != 0:
                nums[non_zero_index] = nums[i]
                non_zero_index += 1

        # Second pass: Fill the rest of the array with zeros
        for i in range(non_zero_index, len(nums)):
            nums[i] = 0