# -*- coding: utf-8 -*-
"""287. Find the Duplicate Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3Zyb5dwfAIkjRgnij_HIuxMRMx3Nh8G
"""

class Solution:
    def findDuplicate(self, nums: List[int]) -> int:
        slow, fast = 0, 0
        while True:
            slow = nums[slow]
            fast = nums[nums[fast]]
            if slow == fast:
                break

        slow2 = 0
        while True:
            slow = nums[slow]
            slow2 = nums[slow2]
            if slow == slow2:
                return slow