# -*- coding: utf-8 -*-
"""2914. Minimum Number of Changes to Make Binary String Beautiful.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BP4h1qdMz6TxeA_HAu4ZgEGpLNagLti
"""

class Solution:
    def minChanges(self, s: str) -> int:
        res = 0

        for i in range(0, len(s), 2):
            if s[i] != s[i+1]:
                res += 1

        return res