# -*- coding: utf-8 -*-
"""3011. Find if Array Can Be Sorted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEc-Gib2iQoOab5J5aNiL6u8IYYb_Pfi
"""

class Solution:
    def canSortArray(self, nums: List[int]) -> bool:
        N = len(nums)

        # Perform bubble sort-like swaps, but only when set bit counts are equal
        for _ in range(N):
            for j in range(1, N):
                if nums[j] < nums[j - 1] and nums[j].bit_count() == nums[j - 1].bit_count():
                    nums[j], nums[j - 1] = nums[j - 1], nums[j]

        # Check if the array is sorted
        for i in range(N - 1):
            if nums[i] > nums[i + 1]:
                return False
        return True