# -*- coding: utf-8 -*-
"""3163. String Compression III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYc51TnFnxs6jdBS0ulrSwaRsDfIouOp
"""

class Solution:
    def compressedString(self, word: str) -> str:
        ans = []
        for c, g in groupby(word):
            s = len(list(g))

            while s > 0:
                f = min(s, 9)
                ans.append(f"{f}{c}")
                s -= f  # Corrected line to decrement s by f

        return "".join(ans)