# -*- coding: utf-8 -*-
"""3174. Clear Digits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b2CB46rUfLyBasmK7CplQX16e9EVyjI
"""

class Solution:
    def clearDigits(self, s: str) -> str:
        stk = []
        for c in s:
            if c.isdigit():
                stk.pop()
            else:
                stk.append(c)
        return "".join(stk)