# -*- coding: utf-8 -*-
"""3243. Shortest Distance After Road Addition Queries I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3szOFkAqxLedWMoLOKswoWAwoII3611
"""

class Solution:
    def shortestDistanceAfterQueries(self, n: int, queries: List[List[int]]) -> List[int]:
        adj = [[ i + 1] for i in range(n)]

        def shortes_path():
            q = deque()
            q.append((0, 0))
            visit = set()
            visit.add((0,0))

            while q:
                cur, length = q.popleft()
                if cur == n - 1:
                    return length
                for nei in adj[cur]:
                    if nei not in visit:
                        q.append((nei, length + 1))
                        visit.add(nei)

        res = []
        for src, dst in queries:
            adj[src].append(dst)
            res.append(shortes_path())
        return res