# -*- coding: utf-8 -*-
"""3386. Button with Longest Push Time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

from typing import List

def button_with_longest_time(events: List[List[int]]) -> int:
    event_durations = {}

    # Initialize the first event
    event_durations[events[0][0]] = events[0][1]

    # Iterate through the rest of the events
    for n in range(1, len(events)):
        duration = events[n][1] - events[n - 1][1]
        button = events[n][0]

        # Update the duration for the button
        if button not in event_durations or duration > event_durations[button]:
            event_durations[button] = duration

    # Determine the button with the longest time
    max_duration = float('-inf')
    result_button = 0

    for button, duration in event_durations.items():
        if duration > max_duration or (duration == max_duration and button < result_button):
            max_duration = duration
            result_button = button

    return result_button