# -*- coding: utf-8 -*-
"""3394. Check if Grid can be Cut into Sections.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def checkValidCuts(self, n, rectangles):
        cuts = [[0] * 2 for _ in range(len(rectangles))]

        self.initializeCuts(rectangles, cuts, 1, 3)
        if self.isValidCut(cuts):
            return True

        self.initializeCuts(rectangles, cuts, 0, 2)
        return self.isValidCut(cuts)

    def initializeCuts(self, rectangles, cuts, xIdx, yIdx):
        for i in range(len(rectangles)):
            cuts[i][0] = rectangles[i][xIdx]
            cuts[i][1] = rectangles[i][yIdx]

    def isValidCut(self, cuts):
        n = len(cuts)
        x = 0
        j = 0

        # Sort the cuts: first by the first element, then by the second element in descending order
        cuts.sort(key=lambda a: (a[0], -a[1]))

        while j < n - 1:
            cur = cuts[j][1]
            while j < n and cuts[j][0] < cur:
                cur = max(cur, cuts[j][1])
                j += 1
            if j < n:
                x += 1

        return x >= 2