# -*- coding: utf-8 -*-
"""3396. Minimum Number of Operations to Make Elements in Array Distinct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def minimumOperations(self, nums: List[int]) -> int:
        n = len(nums)

        if n == 1:
            return 0

        r_index = 0
        seen = set()

        for a in range(n - 1, -1, -1):
            if nums[a] in seen:
                r_index = a + 1
                break
            seen.add(nums[a])

        res = r_index // 3
        if r_index % 3:
            res += 1

        return res