# -*- coding: utf-8 -*-
"""3397. Maximum Number of Distinct Elements After Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyJWqF9g_z2lnoeCSP-fPR_aooACFB1
"""

class Solution:
    def maxDistinctElements(self, nums: List[int], k: int) -> int:
        min_v = min(nums)
        max_v = max(nums)

        ran_size = max_v - min_v + 1
        buc = [0] * ran_size

        for n in nums:
            buc[n - min_v] += 1

        dist_count = 0
        last_use = float('-inf')

        for a in range(ran_size):
            while buc[a] > 0:
                n = a + min_v
                st = max(n - k, last_use + 1)

                if st <= n + k:
                    last_use = st
                    dist_count += 1
                    buc[a] -= 1
                else:
                    break

        return dist_count