# -*- coding: utf-8 -*-
"""347. Top K Frequent Elements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3Zyb5dwfAIkjRgnij_HIuxMRMx3Nh8G
"""

class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        count = {}
        freq = [[] for i in range(len(nums) + 1)]

        for n in nums:
            count[n] = 1 + count.get(n, 0)
        for n, c in count.items():
            freq[c].append(n)

        res = []
        for i in range(len(freq) -1, 0, -1):
            for n in freq[i]:
                res.append(n)
                if len(res) == k:
                    return res