# -*- coding: utf-8 -*-
"""349. Intersection of Two Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faCIIy4DcvKIPFhe-6fKEts_pPyqy_PZ
"""

class Solution:
    def intersection(self, nums1: List[int], nums2: List[int]) -> List[int]:
        seen = set(nums1)
        res = []

        for n in nums2:
            if n in seen:
                res.append(n)
                seen.remove(n)
        return res