# -*- coding: utf-8 -*-
"""367. Valid Perfect Square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

class Solution:
    def isPerfectSquare(self, num: int) -> bool:
        # O(logn)
        l, r = 1, num
        while l <= r:
            m = (l + r) // 2
            if m * m > num:
                r = m - 1
            elif m * m < num:
                l = m + 1
            else:
                return True
        return False