# -*- coding: utf-8 -*-
"""392. Is Subsequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr7W4kpBRfyE7AQYY_7Low_8ypzz8HOs
"""

class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        # Pointers for s and t
        i, j = 0, 0
        while i < len(s) and j < len(t):
            # If characters match, move pointer i for s
            if s[i] == t[j]:
                i += 1
            # Move pointer j for t regardless
            j += 1
        # If we've matched all characters in s, i will equal len(s)
        return i == len(s)