# -*- coding: utf-8 -*-
"""410. Split Array Largest Sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faCIIy4DcvKIPFhe-6fKEts_pPyqy_PZ
"""

class Solution:
    def splitArray(self, nums: List[int], k: int) -> int:
        def canSplit(largest):
            subarray_count = 1
            current_sum = 0
            for n in nums:
                current_sum += n
                if current_sum > largest:
                    subarray_count += 1
                    current_sum = n
            return subarray_count <= k

        left, right = max(nums), sum(nums)
        result = right

        while left <= right:
            mid = left + (right - left) // 2
            if canSplit(mid):
                result = mid
                right = mid - 1
            else:
                left = mid + 1

        return result