# -*- coding: utf-8 -*-
"""436. Find Right Interval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

import bisect
class Solution:
    def findRightInterval(self, intervals: List[List[int]]) -> List[int]:
        intervals = sorted([[b,e,i] for i, [b,e] in enumerate(intervals)])
        res = [-1] * len(intervals)
        b_value = [b for b,e,i in intervals]

        for b,e,i in intervals:
            x = bisect.bisect_left(b_value, e)
            if x != len(b_value):
                res[i] = intervals[x][-1]
        return res