# -*- coding: utf-8 -*-
"""451. Sort Characters By Frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faCIIy4DcvKIPFhe-6fKEts_pPyqy_PZ
"""

class Solution:
    def frequencySort(self, s: str) -> str:
        count = Counter(s)

        buckets = defaultdict(list)
        for char, freq in count.items():
            buckets[freq].append(char)

        res = []
        for freq in range(len(s), 0, -1):
            if freq in buckets:
                for char in buckets[freq]:
                    res.append(char * freq)

        return "".join(res)