# -*- coding: utf-8 -*-
"""48. Rotate Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kj-xnsM8kbFVwHhwI85YYmaEBCWtCZg0
"""

class Solution:
    def rotate(self, matrix):

        matrix.reverse()
        for i in range(len(matrix)):
            for j in range(i):
                matrix[i][j], matrix[j][i] = matrix[j][i],matrix[i][j]