# -*- coding: utf-8 -*-
"""515. Find Largest Value in Each Tree Row.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kj-xnsM8kbFVwHhwI85YYmaEBCWtCZg0
"""

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

class Solution:
    def largestValues(self, root: Optional[TreeNode]) -> List[int]:
        if not root:
            return []

        queue = deque([root])
        largest_values = []

        while queue:
            level_size = len(queue)
            max_value = float('-inf')

            for _ in range(level_size):
                node = queue.popleft()
                max_value = max(max_value, node.val)

                if node.left:
                    queue.append(node.left)
                if node.right:
                    queue.append(node.right)

            largest_values.append(max_value)

        return largest_values