# -*- coding: utf-8 -*-
"""540. Single Element in a Sorted Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

class Solution:
    def singleNonDuplicate(self, nums: List[int]) -> int:
        l, r = 0, len(nums) - 1

        while l < r:
            m = l + (r - l) // 2

            if m % 2 == 1:
                m -= 1

            if nums[m] == nums[m + 1]:
                l = m + 2
            else:
                r = m

        return nums[l]