# -*- coding: utf-8 -*-
"""611. Valid Triangle Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOUn44tXxoD55j-RB3WonMde9MgWdNmP
"""

class Solution:
    def triangleNumber(self, nums: List[int]) -> int:
        nums.sort()
        res = 0
        for a in range (len(nums)-1, 1, -1):
            b, c = 0, a-1
            while b < c:
                if nums[b] + nums[c] > nums[a]:
                    # we have a valid triangle
                    res += c - b
                    c -= 1
                else:
                    # we don't have a valid traiangle, we want larger values so we move b += 1
                    b += 1
        return res