# -*- coding: utf-8 -*-
"""643. Maximum Average Subarray I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pDPqcnacs5XN5LXupPLvzHS1YBX5iJd
"""

class Solution:
    def findMaxAverage(self, nums: List[int], k: int) -> float:
        # Calculate the initial window sum of the first k elements
        max_sum = current_sum = sum(nums[:k])

        # Slide the window over the array, updating the sum
        for i in range(k, len(nums)):
            current_sum += nums[i] - nums[i - k]
            max_sum = max(max_sum, current_sum)

        # Return the maximum average
        return max_sum / k