# -*- coding: utf-8 -*-
"""724. Find Pivot Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxAC4yR_-Z5dojt-oQDzgT-fr_IO9qCC
"""

class Solution:
    def pivotIndex(self, nums: List[int]) -> int:
        total_sum = sum(nums)
        left_sum = 0

        for i, num in enumerate(nums):
            # Calculate right sum as total_sum - left_sum - current number
            if left_sum == total_sum - left_sum - num:
                return i
            left_sum += num

        return -1