# -*- coding: utf-8 -*-
"""80. Remove Duplicates from Sorted Array II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZY38eysGcNm88W8iNVqAhduj33Gr8yT
"""

class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        l, r = 0, 0

        while r < len(nums):
            count = 1
            while r + 1 < len(nums) and nums[r] == nums[r + 1]:
                r += 1
                count += 1

            for i in range(min(2, count)):
                nums[l] = nums[r]
                l += 1
            r += 1
        return l