# -*- coding: utf-8 -*-
"""86. Partition List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHooiJVSGNXBCJeoSWF9eIncC0IoVGRw
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def partition(self, head: Optional[ListNode], x: int) -> Optional[ListNode]:
        left, right = ListNode(), ListNode()
        ltail, rtail = left, right

        while head:
            if head.val < x:
                ltail.next = head
                ltail = ltail.next
            else:
                rtail.next = head
                rtail = rtail.next
            head = head.next

        ltail.next = right.next
        rtail.next = None
        return left.next