# -*- coding: utf-8 -*-
"""2880. Select Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iP24vtSYrykI5jEonykUHLSfRx77J41m
"""

import pandas as pd

def selectData(students: pd.DataFrame) -> pd.DataFrame:
    result = students[students['student_id'] == 101][['name', 'age']]
    return result