# -*- coding: utf-8 -*-
"""2891. Method Chaining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iP24vtSYrykI5jEonykUHLSfRx77J41m
"""

import pandas as pd

def findHeavyAnimals(animals: pd.DataFrame) -> pd.DataFrame:
    filtered_animal=animals[animals['weight']>100].sort_values(by='weight',ascending=False)
    return pd.DataFrame(filtered_animal['name'])