# -*- coding: utf-8 -*-
"""595. Big Countries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpVFyNM24h-nF9dKZx0842SxfCalg1_e
"""

import pandas as pd

def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    big_countries_data = world[(world['area'] >= 3000000) | (world['population'] >= 25000000)]
    return big_countries_data[['name', 'population', 'area']]